### ISSUE TITLE
I don't know who you are.

### ISSUE THREAD

**Issue by sourabhsharma24** [Hack-Weekly/saffron-wolf-sudoku#15]
HI, Garrett 
I'm Sourabh , I am beginner on GitHub and trying to contribute on small project  so that I can get a little bit idea about open source I earlier tried to contribute in your one of the project but you marked  it  as do not merge ,if you like you can remove your do not merge tag I will delete it my side , my pull request .
thanks

**Comment by GretSeat** [comment]
It's not open source. Please stop.
